spring:
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
  application:
    flyway:
      enabled: true

management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show.details: always
  metrics.export.prometheus.enabled: true

---
spring:
  config.activate.on-profile: local
  security:
    oauth2:
      client:
        registration:
          portalasig_engine:
            authorization-grant-type: client_credentials
            client-id: portalasig_engine
            client-secret: '{cipher}090795838436a9da213cd43610668adc041505c4a1b52255e63ca5d170b4d3997a0ef48effa75a8309e7fe6197a896b8'
        provider:
          portalasig_engine:
            token-uri: http://localhost:5860/portalasig/uaa/oauth2/token
          portalasig_client:
            token-uri: http://localhost:5860/portalasig/uaa/oauth2/token

ENV: local
backend-uri: http://localhost

portalasig.security.oauth2.authorization-server.jwt.issuer-uri: ${backend-uri}:5860/portalasig/uaa
portalasig.uaa.ms.v1.url: ${backend-uri}:5860/portalasig/uaa/v1

